# Generated by Django 6.0 on 2025-12-18 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('foto', models.ImageField(upload_to='mascotas/posts/')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='app1.mascota')),
            ],
            options={
                'verbose_name': 'Post de Mascota',
                'verbose_name_plural': 'Posts de Mascotas',
                'ordering': ['-fecha'],
            },
        ),
    ]
