# Generated by Django 6.0 on 2025-12-18 05:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_postmascota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmascota',
            name='fecha',
            field=models.DateField(default=datetime.date.today, help_text='Fecha en que ocurrió este momento'),
        ),
    ]
